### ISSUE TITLE
Create web site

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/seshat#12]
Hello @keilw. Should we create a web site on https://unitsofmeasurement.github.io/seshat with Javadoc? If yes, then if I understood correctly the process would be:

1. [Create an orphan branch](https://help.github.com/en/articles/creating-project-pages-using-the-command-line) with `git checkout --orphan gh-pages`.
2. Commit a home page and javadoc on that branch.
3. Other action needed?

Any recommendation?

**Comment by desruisseaux** [comment]
Created the branch on https://github.com/unitsofmeasurement/seshat/tree/gh-pages for testing purpose. Waiting to see if the `index.html` page appears after some time.

**Comment by desruisseaux** [comment]
I guess that enabling those pages would require someone with administrative privilege (I do not have). @keilw could you take a loot under the "Setting" tab please (if you agree)?

**Comment by keilw** [comment]
Have to check later when I'm on my own PC. If admin rights can be added to a particular repo, @desruisseaux will get it here. P.s.: what about the TCK, I understand, Seshat may always have problems with those 2 tests that fail as in https://117-41443578-gh.circle-artifacts.com/0/home/circleci/repo/target/tck-output/emailable-report.html? For JSR 363 I would not necesarily change it unless you think Seshat may take many more months before it can also implement 385, but since `equals()` and `hashCode()` are not vital parts of our actual API I would say removing those two for the `Quantity` check should be acceptable without affecting the value of the TCK.

**Comment by desruisseaux** [comment]
I was not aware of those two test failures, thanks for spotting them. I will check. Are those tests run automatically when new commits are pushed?

I just saw you comment about the TCK test failures on issue #7. Sorry for having missed it.

**Comment by keilw** [comment]
Yes the current Seshat version fails the TCK (of JSR 363). I don't know, if any reasonable change could be made to address that e.g. take equals and hashcode into consideration, but if you can, please do, otherwise we may have to discuss excluding certain tests (as this was the case for Jakarta EE recently ;-)

**Comment by desruisseaux** [comment]
Hello @keilw. If you have a chance, can you take a look at the "Settings" tab of Seshat, scroll down to "GitHub Pages" and verify that "hg-pages branch" is selected? I would like to make a web site alive if possible.

**Comment by keilw** [comment]
I hope "hg-pages" was a typo? Will have a look, is the 1.0 release also going to be on MavenCentral or another repository?

**Comment by desruisseaux** [comment]
Yes, `hg` was a typo - I mean `gh-pages`, thanks for spotting that.

It would be nice if it could be distributed on Maven Central (task #13), but I think only you can do that as the owner of `tech.uom` group ID?

**Comment by keilw** [comment]
That is quite possible, if you have a bintray account, I'd be happy to add you to the UoM organization, but for Sonatype they have their own credentials and access tickets, mine works there, so I am happy to deploy Seshat, if you would like to help with Bintray, tell me your account name.

**Comment by desruisseaux** [comment]
I'm not familiar with bintray; I have a sonatype account. But if it is easier to go through bintray, I can register there.

**Comment by desruisseaux** [comment]
Hello @keilw. Is there any update about the Seshat web site publishing issue? I created GitHub pages on https://github.com/unitsofmeasurement/seshat/tree/gh-pages but I think we need administrator to look on https://github.com/unitsofmeasurement/seshat/settings scroll down to "GitHub" pages and ensure that "gh-pages branch" is selected.

**Comment by keilw** [comment]
I gave you "maintain" privileges to seshat, please try if thats's enough, it is just one notch below admin, if that does not work to publish or edit branches, let me know, then I could also try admin.

**Comment by desruisseaux** [comment]
A (very primitive) web site is online at https://unitsofmeasurement.github.io/seshat/. Thanks for your help!

**Comment by keilw** [comment]
Great it worked. Are there plans for a 1.0 GA of Seshat or even 2.x using JSR 385 any time soon?

**Comment by desruisseaux** [comment]
(Oups! your comment makes me realize that I deployed Javadoc from snapshot instead than 1.0 release - this is fixed).

1.0 GA was tagged 5 months ago actually, but have not been deployed to Maven central yet. This is the topic of #13. The main issue here is for me to learn how to do that with Bintray.

For using JSR 385, my hope is to work on it this summer. But I'm notoriously bad with delays, so it is hard to said if I will be ontime.

**Comment by keilw** [comment]
Ok let me know, if you need help with Bintray, e.g. creating an artifact, although that might already exist. https://github.com/unitsofmeasurement/unit-tck-usage/tree/seshat demonstrates the TCK is passed, it is a generous variation of the `QUANTITY` profile in the TCK, but I assume `BASE_QUANTITY` would pass under any circumstance because it only tests for  the SI base quantities and not all that JSR 363 or 385 offer?

**Comment by desruisseaux** [comment]
I'm not sure what is the difference between the `QUANTITY` and `BASE_QUANTITY` profiles? The [TCK 1.1 is also executed during Seshat Maven build](https://github.com/unitsofmeasurement/seshat/blob/1.0/pom.xml#L120), but no profile is specified. Running `mvn test` or `mvn install` on Seshat produces the following output:

```
JSR 363 TCK version 1.0.2-SNAPSHOT Summary
-------------------------------------------------------

TOTAL TESTS EXECUTED : 84
TOTAL TESTS SKIPPED  : 0
TOTAL TESTS SUCCESS  : 84
TOTAL TESTS FAILED   : 0

-- JSR 363 TCK finished --
```
