### ISSUE TITLE
seshat with Java 8

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/seshat#8]
Hi, 
      I would like to test seshat and I was wondering if it would be possible to have a java8 compatible version. If it's not too much work would be nice to have it available. 

Regards
Luca

**Comment by desruisseaux** [comment]
Done in a JDK8 branch: https://github.com/unitsofmeasurement/seshat/tree/JDK8
However current version requires compiling with Java 10, even if the JAR file produced by Maven target Java 8. Is it an issue?

I leave this issue open for investigating how to retrofit in a multi-versions JAR file.

**Comment by lfoppiano** [comment]
I guess I can live with that. 
I was wondering what is the library requiring java 10? is it sis-build-helper?

**Comment by desruisseaux** [comment]
`sis-build-helper` indeed requires Java 10, but only at build time. This one would be difficult to run on JDK8 because some tools API (the `jdk.*` modules) changed considerably between recent JDK versions, and are much easier to use in a Maven project since Java 9.

For the library itself (excluding the build tools), except for the `module-info` file, the differences between the two branches are very minors. Mostly conveniences like additional methods in `java.util.Objects`. The most significant differences are the use of `Math.fma`, which make a slight difference on accuracy of some operations, and the use of `System.Logger` for those who want different logging framework.

I plan to merge `JDK8` branch back to `master` as multi-releases JAR file next Saturday. I experimented creation of multi-releases JAR file last Sunday on Unit-API and found that it was relatively easy to do.

**Comment by lfoppiano** [comment]
OK, I was just curious. 

I will test this week and let you know.

**Comment by lfoppiano** [comment]
Just noticed the groupId is `tech.uom` instead of `tec.uom`, is it normal?

**Comment by desruisseaux** [comment]
We would need to ask Werner to confirm for being sure. But my understanding is that `tec.uom` were used for [version 1 of various artifact](https://search.maven.org/search?q=g:tec.uom) while `tech.uom` is used for [version 2](https://search.maven.org/search?q=g:tech.uom)

@keilw can you confirm?

**Comment by desruisseaux** [comment]
The master now build a multi-release JAR file with JDK8 as the base version and JDK10 as an optional version. The JDK8 branch has been deleted, since it is not merged within master.
